a collection of small fixes
travelping/ergw pull request #274
Opened 2020-12-04 13:10 UTC by RoadRunnr

2020-12-08 17:34 UTC, vkatsuba requested changes
Looks like need to fix: 
```sh
===> src/ergw.erl:48: Warning: ergw:get_node_id/0 is unused export (Xref)
The command "./rebar3 do xref, ct" exited with 1.
```

2020-12-08 17:38 UTC, fholzhauser approved these changes

2020-12-09 11:48 UTC, RoadRunnr commented
dropped a few cset, most notable the node_id change. That will come as a separate PR.

2020-12-09 13:07 UTC, vkatsuba approved these changes

2020-12-09 14:51 UTC, merged