Add logic for delete contexts by criteria
travelping/ergw pull request #277
Opened 2020-12-14 21:42 UTC by vkatsuba

**Extend delete contexts REST API and API for delete contexts contexts by criteria:**   
`/api/v1/contexts?version=VERSION&imsi=IMSI&pfcp=PFCP`  
**Example:** 
`/api/v1/contexts?version=v1&imsi=111111111111111&pfcp=topon.sx.prox01.epc.mnc001.mcc001.3gppnetwork.org`  
____
Query parameters:
| Name   |      Type      |  Description |
|-----------|:---------------:|-----------------:|
| imsi                 | integer | ... |
| pfcp                 | string | ... |
| version            | string | ... |

2020-12-15 08:47 UTC, RoadRunnr commented on priv/static/specs/http_api_spec.yaml
> +        - name: pfcp
The parameter names makes no sense IMHO. PFCP is a protocol, the entity speaking that protocol is a UPF or in 5G terms "a NF Instance of type `UPF`".

The parameter name should therefor IMHO be `upf-fqdn`.

When a 5G compatible naming is used, then using two arguments, `target-nf-type`, and `target-nf-instance-id` or `target-nf-fqdn` (see TS 29.510, Table 6.2.3.2.3.1-1 for example).

NOTE: In 5G nf-instance-id is a FQDN, but does not need to match the FQDN for instance selection. Therefor nf-fqdn and fn-instance-id could differ.

2020-12-15 08:50 UTC, RoadRunnr commented on priv/static/specs/http_api_spec.yaml
> +          default: 'topon.sx.prox01.epc.mnc001.mcc001.3gppnetwork.org'
The example might be misleading. The FQDN represents the name of a specific interface on an UPF instance, the FQDN of the UPF instance itself would be different. In this case the UPF instance name is most likely `prox01.epc.mnc001.mcc001.3gppnetwork.org`

2020-12-15 08:52 UTC, RoadRunnr commented on priv/static/specs/http_api_spec.yaml
> +        - name: pfcp
One more thing, the UPF node id is currently missing from the PFCP interaction. This is a oversight that should be fixed soonish (a PR in the UPG project is already pending).

2020-12-16 11:45 UTC, RoadRunnr commented on src/http_api_handler.erl
> +                version    => list_to_atom(binary_to_list(proplists:get_value(<<"version">>, Qs, <<>>))),
better use `list_to_existing_atom`

2020-12-16 11:50 UTC, RoadRunnr requested changes

2020-12-16 11:50 UTC, RoadRunnr commented on src/ergw_api.erl
> +        {_, State} = sys:get_state(Pid),
No,

Don't access process state like state. Either filter through the context_reg or when that doesn't have enough information, use a dedicated API on the context to get that information.

2020-12-16 11:50 UTC, RoadRunnr commented on priv/static/specs/http_api_spec.yaml
> +          description: 'UPF FQDN'
the implementation actually treats upf-fqdn as regex. Might be worth mentioning here.

2021-05-14 13:24 UTC, vkatsuba commented
Closed due to lack of activity.

2021-05-14 13:24 UTC, closed without merging