Fix GTP path echo timer reset
travelping/ergw pull request #421
Opened 2021-07-30 15:51 UTC by fholzhauser

This PR would fix the issue that short sessions on a right side path (e.g. with GSN path change on create session response) resets the scheduled echo and can cause lack of path management in case only such sessions are done on a path.

- the gtp path sends an echo immediately when the path starts, speeding up the detection of a broken destination
- the echoes are scheduled relative to the last sent echo which prevents that path management stops due to rescheduling the echos just with the interval at each change

2021-08-02 06:15 UTC, RoadRunnr requested changes
I'm not sure that this change goes into the right direction.
The intention of the Echo logic was always to restart Echo interval when a state change occurs. The reasoning is that a change of state somehow indicates a activity on the peer and that that defines the last know state of the peer. The next Echo will then validate that state (or change it).

The real problem that this PR tries to fix is that pending requests and context will impact the state of the peer. And that is IMHO the real problem, activity triggered by us should never change the peers state, only responses and timeouts from the peer should impact the peer state.

2021-08-02 06:15 UTC, RoadRunnr commented on src/gtp_path.erl
> +    State#state{echo = {Ref, os:system_time(millisecond)}}.
this should use `erlang:monotic_time`

2021-08-02 06:15 UTC, RoadRunnr commented on src/gtp_path.erl
> +    TS = os:system_time(millisecond),
this should use `erlang:monotic_time`

2021-08-03 05:25 UTC, fholzhauser commented on src/gtp_path.erl
> +    State#state{echo = {Ref, os:system_time(millisecond)}}.
yes, thanks for spotting it

2021-08-03 05:25 UTC, fholzhauser commented on src/gtp_path.erl
> +    TS = os:system_time(millisecond),
indeed

2021-08-03 05:39 UTC, fholzhauser commented
> I'm not sure that this change goes into the right direction.
> The intention of the Echo logic was always to restart Echo interval when a state change occurs. The reasoning is that a change of state somehow indicates a activity on the peer and that that defines the last know state of the peer. The next Echo will then validate that state (or change it).
> 
> The real problem that this PR tries to fix is that pending requests and context will impact the state of the peer. And that is IMHO the real problem, activity triggered by us should never change the peers state, only responses and timeouts from the peer should impact the peer state.

Yes indeed, the intention of this is not to change the existing logic, which is at the moment mixing echo probe results and contexts to determine the state, and as you mentioned could (and probably should) be fundamentally reconsidered. It only intends to fix a particular situation that can render broken path detection completely dysfunctional in a specific scenario. I'm also not quite sure if it changes the path state logic, but only the scheduling of the echo probes to make sure that the interval changes at state transitions don't result in echoes not being sent.

2021-08-04 06:58 UTC, mgumz commented
@fholzhauser is this PR address https://github.com/travelping/smc/issues/37 ?

2021-08-04 07:17 UTC, RoadRunnr commented
> @fholzhauser is this PR address [travelping/smc#37](https://github.com/travelping/smc/issues/37) ?

It might, but it is the wrong approach (IMHO).

The underlying problem is that outgoing GTP requests are considered as a livesign of the peer and therefore reset the Echo timer. The correct approach would be to only use GTP packets from the peer (requests and responses) as indication of liveliness.

This PR does not change that. Instead it decouples the GTP echo timer from the other activity indications.

2021-09-15 07:53 UTC, RoadRunnr commented
for the 3.x and master branch this is resolved in #428

Is this PR till needed or can we close it?

2021-09-15 12:49 UTC, vkatsuba commented
PR https://github.com/travelping/ergw/pull/428 is related to master(`3.X`) version. Current PR is related to `2.X`. Depending on how critical the problem for `2.X` - we can close this PR or provide release `2.8.15` with including fix. However I not sure that this is should be done. I will close current PR and  if this will be necessary to fix it for `2.8.X` too, we always can back to current implementation.

2021-09-15 12:49 UTC, closed without merging